site_name: Liquigraph
nav:
  - Home: index.md
  - Download: download.md
  - Migrate to Liquibase: migration-to-liquibase.md
  - Quickstart:
    - CLI: quickstart/cli.md
    - Maven plugin: quickstart/maven.md
    - Spring Boot: quickstart/spring-boot.md
  - Reference: reference.md
  - "[archive] 2.x manual": 2.x.md
repo_name: 'liquigraph'
repo_url: 'https://github.com/liquibase/liquigraph'
theme:
  name: material
  icon:
    logo: fontawesome/solid/tint
  custom_dir: overrides
plugins:
  - markdownextradata: {}
extra:
  versions:
    latest_3x: 3.1.2
    latest_4x: 4.0.6
    jdbc_4x: 4.0.5
    jdbc_3x: 3.5.2
markdown_extensions:
  - abbr
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: ⚓
